### ISSUE TITLE
NTv2 grid shift file for Romania

### ISSUE THREAD

**Issue by TNick** [danieluct/ntv2generator#1]
Based on the presentation found [here](https://europe.foss4g.org/2014/slides/Daniel%20Urda%20-%20PROJ4%20Issues.The%20case%20of%20Romania2.pdf) I would assume that a NTv2 grid shift file has been generated for Romania.

Is this file available somewhere for download?
I would rather not go through all the steps myself as the process seems to be rather complex.

**Comment by tudorbarascu** [comment]
Salut Nicu,
poti sa iei gridul de la https://github.com/tudorbarascu/stereo70-etrs89/tree/master/grids

Atentie ca pe z nu face transformarea (i-a cam fost lene lui @danieluct ).

**Comment by TNick** [comment]
@tudorbarascu Transformarea pe z e ceva ce se poate rezolva intr-un week-end prin studierea/modificarea scripturilor?

**Comment by tudorbarascu** [comment]
@ TNick 
Raspuns scurt: Nu stiu.

Raspuns lung:
Nu m-am uitat deloc la cod. Din ce-am vorbit cu @danieluct la momentul respectiv in proj4 nu era suport pentru z pe natgriduri si de un an il tot bat la cap ( ma rog sa-si faca timp ).

Daca stii C bine cred ca poti rezolva intr-un weekend.
Eu tot in @danieluct am speranta, pt. ca teoretic lui i-ar lua cel mai putin timp.
Daca doresti, putem discuta mai in detaliu.

**Comment by TNick** [comment]
Da, sunt pretin cu C-ul da' ma asteptam sa fie vorba de Python.
Poate contribuie si @danieluct o opinie si ceva indicatii si ii dam de capat.

**Comment by tudorbarascu** [comment]
Tu o sa scrii in Python, dar cred ca trebuie sa citesti ce trebuie din proj4 (C).
